# Use root/example as user/password credentials
version: '3.1'

services:

  myboca:
    image: registry.gitlab.com/rlaiola/boca-db:mysql
#    https://stackoverflow.com/questions/44884719/exited-with-code-0-docker/55907197:
    tty: true
    #command: --privileged
    #restart: always
    ports:
      - 80:80
    volumes:
      - "/home/marcela/Documents/bocalab/home:/home"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  bocamysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secondary
    volumes:
      - "/home/marcela/Documents/bocalab/data:/var/lib/mysql-files"